sonar.projectKey=WeatherBuraApp_server
sonar.projectName=WeatherBuraApp Server
sonar.sources=server/src/main/java
sonar.tests=server/src/test/java
sonar.java.binaries=server/build/classes/java/main
sonar.java.test.binaries=server/build/classes/java/test
sonar.sourceEncoding=UTF-8
sonar.coverage.jacoco.xmlReportPaths=server/build/reports/jacoco/test/jacocoTestReport.xml
